### ISSUE TITLE
Implement automated backup for files.

### ISSUE THREAD

**Issue by joe-pierce** [People-Places-Solutions/floodmodeller-api#31]
Currently the API works directly on the loaded Flood Modeller files (DAT, IEF, IED etc.) and will save any changes in-place if the `.update()` method is used, this means there may be times when undesirable changes are made to the files (unknowingly by user or introduced via a bug). In these cases it would result in loss of data if there is no external back up system in place. As a user, I want the floodmodeller-api to guarantee that bugs do not cause any data loss or corruption of files. 

To do this, a backup system should be implemented in `_base.FMFile` class, that upon loading any file, will immediately create a local backup that will persist beyond the scope of the api session. This means in the case of any problems, there will be a backup to go back to. 

Taking this a step further, it would be good to have a relatively simple way that a user can fetch or revert any backups. The first iteration could be simply saving the file with a timestamp in the OS temp directory. A more sophisticated option would be to have a local sqlite database that stores all backups from the API. 

```[tasklist]
### Tasks
- [x] Implement basic backup function in FMFile
- [x] Explore options to imrpove management of backups
- [x] Expose backups to user via function in API 
- [x] Write test case in test module
- [x] Documentation
```

**Comment by matthewjwhittle-jacobs** [comment]
The basic implementation of this feature is working and tested. Currently, the workflow is as follows:
```{python}
from floodmodeller_api.backup import File
from floodmodeller_api import DAT 

dat_path = "test/test_data/EX1.DAT"
# Load the DAT file
# This makes an automatic backup in users temp directory 
# if an equivalent one doesn't already exist (tested by filecmp.cmp)
dat1 = DAT(dat_path)
# You then need to use a File object to manage the backups
# Create the File object to manage backups
dat_file = File(dat_path)
# Restore from the most recent backup
dat_file.restore(to ="restored-file.DAT")
```
I think it would probably be more user-friendly to add the file object as a property of the FMFile to expose the restore method via the DAT, IEF, ... etc classes. Then the workflow would be closer to this. 
```
from floodmodeller_api import DAT 
dat1 = DAT("test/test_data/EX1.DAT")
dat1.file.restore(to = "restored-file.DAT")
```
At the moment it just restores it from the most recent backup and you have to dive into the file system to retrieve a specific back up. But I think something like this would be more user friendly
```
dat1 = DAT("test/test_data/EX1.DAT")
backup_list = dat1.file.get_backups()
print(backup_list )
# [Backup("xxxxx_2020-01-01-12-42-32"), Backup(...), ...]
backup_list[0].restore(to = "this/file.DAT")
```
@joe-pierce any thoughts on this?

**Comment by matthewjwhittle-jacobs** [comment]
I've updated it to follow this workflow for retrieving a backup
```
from floodmodeller_api import DAT 
dat1 = DAT("test/test_data/EX1.DAT")
dat1.file.restore(to = "restored-file.DAT")
```

**Comment by matthewjwhittle-jacobs** [comment]
And added a better method for retrieving specific backups 
```
# Load the DAT
# Automatically backs up the file if it has changes since the last backup
dat = DAT("a_dat_file.DAT")
# List the available backups
backups = dat.file.list_backups()
# Restore the latest backup to a file
backups[0].restore(to = "restore-file.DAT")
# Restore an older backup
backups[6].restore(to = "restore-file.DAT")
```
